# Generated by Django 2.2.3 on 2019-07-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('user_name', models.TextField()),
                ('user_id', models.TextField()),
                ('server_name', models.TextField()),
                ('server_id', models.TextField()),
            ],
        ),
    ]
